### PR TITLE
Examples Consumers table edited

### PR DESCRIPTION
**Pull request by GustavoMarcante**
Included example sites and some status updated.

### CODE REVIEW

**Comment by dawehner** [comment]
Thanks a ton for this pull request!

+1 for this change! I really like having demo links, if possible.

Anyone else has an opinion?

**Comment by justafish** [comment]
:+1:

**Comment by e0ipso** [comment]
Thanks a lot!

**Comment by GustavoMarcante** [comment]
I thank you! You make things became so easy...

**Pull request merged**
