### PR TITLE
Update index.md with Vue status

### PR DESCRIPTION
**Pull request by GustavoMarcante**
Update Vue status in Example Consumers and change "Running demo" with "Demo is running".

### CODE REVIEW

**Comment by dawehner** [comment]
@GustavoMarcante I'm curious why you made this particular change, is "demo is running" some particular better english? I'm channeling the british here: @justafish

**Comment by GustavoMarcante** [comment]
@dawehner "Running demo" was my first option, if it sounds better, lets keep!

I made the update of Vue status because the demo was running, but I saw that it changed (is not running now). So I think I can cancel this request.

**Comment by dawehner** [comment]
So no changes needed?

**Comment by GustavoMarcante** [comment]
@dawehner Ops, I edited before your comment. Yes, I closed it.

**Comment by dawehner** [comment]
Cool!

**Pull request closed without merging**
