### PR TITLE
add tagline at the top, move installation up

### PR DESCRIPTION
**Pull request by yann-yinn**
1 - today at the top of the homepage, we have no summary of how contenta can help people, we have a "our mission" which is a link to a long post.

=> I added a short description of  what contenta is and how it helps right at the top

2 - each time i came, i first see quick install and then say me : oups not, i want a full standard installation, not the quick Our Mission

=> i move standard installation BEFORE quick one

### CODE REVIEW

**Comment by dawehner** [comment]
Personally I think we should separate the changes. I personally think we should put the quick install higher up, but I totally like the idea explaining it better what contenta is.

**Comment by e0ipso** [comment]
I have no strong feelings in one way or the other.

**Comment by yann-yinn** [comment]
sorry, I should make a clean PR but so little time  this days ...
I agree this should be two separated concerns, i remove my inversion with a second commit

**Comment by e0ipso** [comment]
:shipit:

**Pull request merged**
